web:
  image: shin1x1/laravel-on-php7-cli
  command: php artisan serve --host=0.0.0.0
  ports:
    - "8000:8000"
  links:
    - db_app
    - db_app_test
  volumes:
    - .:/code
  environment:
    DB_HOST: db_app

db_app:
  image: postgres:9.5
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: app
    LC_ALL: C

db_app_test:
  image: postgres:9.5
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: app_test
    LC_ALL: C
